-- =============================================
-- CRIAÇÃO DA TABELA DE SOBRENOMES DO ORISÁ
-- Os sobrenomes são filtrados pela qualidade do Orisá
-- (ou pelo Orisá diretamente, caso não haja qualidade)
-- =============================================

CREATE TABLE IF NOT EXISTS sobrenomes_orisa (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  orisa TEXT NOT NULL,        -- Nome do Orisá (ex: 'Bará', 'Ogum', 'Oxum'...)
  qualidade TEXT NOT NULL,    -- Qualidade/caminho (ex: 'Lodê', 'Aganjú', 'Ibejê'...)
  nome TEXT NOT NULL,         -- O sobrenome em si (ex: 'Alalupagema', 'Açuã'...)
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para performance nas buscas filtradas
CREATE INDEX IF NOT EXISTS idx_sobrenomes_orisa_orisa ON sobrenomes_orisa(orisa);
CREATE INDEX IF NOT EXISTS idx_sobrenomes_orisa_qualidade ON sobrenomes_orisa(qualidade);
CREATE INDEX IF NOT EXISTS idx_sobrenomes_orisa_orisa_qualidade ON sobrenomes_orisa(orisa, qualidade);

-- =============================================
-- POLÍTICAS RLS
-- =============================================
ALTER TABLE sobrenomes_orisa ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Leitura pública de sobrenomes_orisa"
  ON sobrenomes_orisa FOR SELECT
  USING (true);

CREATE POLICY "Apenas autenticados podem inserir sobrenomes_orisa"
  ON sobrenomes_orisa FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Apenas autenticados podem atualizar sobrenomes_orisa"
  ON sobrenomes_orisa FOR UPDATE
  USING (auth.role() = 'authenticated');

CREATE POLICY "Apenas autenticados podem deletar sobrenomes_orisa"
  ON sobrenomes_orisa FOR DELETE
  USING (auth.role() = 'authenticated');

-- =============================================
-- INSERT DOS SOBRENOMES
-- Estrutura: (orisa, qualidade, nome)
-- =============================================

INSERT INTO sobrenomes_orisa (orisa, qualidade, nome) VALUES

-- BARÁ LODÊ
('Bará', 'Lodê', 'Alalupagema'),
('Bará', 'Lodê', 'Açuã'),
('Bará', 'Lodê', 'Beí'),
('Bará', 'Lodê', 'Bô'),
('Bará', 'Lodê', 'Bemi'),
('Bará', 'Lodê', 'Berí'),
('Bará', 'Lodê', 'Bomi'),
('Bará', 'Lodê', 'Bicuim'),
('Bará', 'Lodê', 'Borocum'),
('Bará', 'Lodê', 'Denim'),
('Bará', 'Lodê', 'Djeteiú'),
('Bará', 'Lodê', 'Dalé'),
('Bará', 'Lodê', 'Elupanda'),
('Bará', 'Lodê', 'Elauê'),
('Bará', 'Lodê', 'Fumí'),
('Bará', 'Lodê', 'Fumilalô'),
('Bará', 'Lodê', 'Lonã'),
('Bará', 'Lodê', 'Lakê'),
('Bará', 'Lodê', 'Modibau'),
('Bará', 'Lodê', 'Motim'),
('Bará', 'Lodê', 'Nabuê'),
('Bará', 'Lodê', 'Obí'),
('Bará', 'Lodê', 'Obê-emí'),
('Bará', 'Lodê', 'Sapatá'),
('Bará', 'Lodê', 'Xê'),

-- BARÁ ADAGUE
('Bará', 'Adague', 'Ajanadá'),
('Bará', 'Adague', 'Aguidê'),
('Bará', 'Adague', 'Aguidê-omí'),
('Bará', 'Adague', 'Borocum'),
('Bará', 'Adague', 'Berim'),
('Bará', 'Adague', 'Bí'),
('Bará', 'Adague', 'Belomí'),
('Bará', 'Adague', 'Birim'),
('Bará', 'Adague', 'Bomí'),
('Bará', 'Adague', 'Caminoloa'),
('Bará', 'Adague', 'Dikí'),
('Bará', 'Adague', 'Deí'),
('Bará', 'Adague', 'Epanadá'),
('Bará', 'Adague', 'Inguê'),
('Bará', 'Adague', 'Kraví'),
('Bará', 'Adague', 'Larom'),
('Bará', 'Adague', 'Lonã'),
('Bará', 'Adague', 'Lapô'),
('Bará', 'Adague', 'Naum'),
('Bará', 'Adague', 'Sebiú'),
('Bará', 'Adague', 'Tukí'),
('Bará', 'Adague', 'Tuebí'),

-- BARÁ AGELÚ
('Bará', 'Agelú', 'Apanadá'),
('Bará', 'Agelú', 'Bí-omí'),
('Bará', 'Agelú', 'Biomí'),
('Bará', 'Agelú', 'Bí'),
('Bará', 'Agelú', 'Darê'),
('Bará', 'Agelú', 'Deí'),
('Bará', 'Agelú', 'Demí'),
('Bará', 'Agelú', 'Emim'),
('Bará', 'Agelú', 'Funiqué'),
('Bará', 'Agelú', 'Gebí'),
('Bará', 'Agelú', 'Grajé'),
('Bará', 'Agelú', 'Idê'),
('Bará', 'Agelú', 'Lolú'),
('Bará', 'Agelú', 'Lonan'),
('Bará', 'Agelú', 'Lobí'),
('Bará', 'Agelú', 'Niquê'),
('Bará', 'Agelú', 'Remí'),
('Bará', 'Agelú', 'Tolalú'),
('Bará', 'Agelú', 'Tolabí'),
('Bará', 'Agelú', 'Unã'),

-- BARÁ LANÃ
('Bará', 'Lanã', 'Aguidê'),
('Bará', 'Lanã', 'Aguidê-omí'),
('Bará', 'Lanã', 'Apanadá-lanã'),
('Bará', 'Lanã', 'Açanã'),
('Bará', 'Lanã', 'Bí'),
('Bará', 'Lanã', 'Bilanã'),
('Bará', 'Lanã', 'Belomí'),
('Bará', 'Lanã', 'Borocum'),
('Bará', 'Lanã', 'Borocum-lanã'),
('Bará', 'Lanã', 'Crony'),
('Bará', 'Lanã', 'Diquí'),
('Bará', 'Lanã', 'Dê'),
('Bará', 'Lanã', 'Deí'),
('Bará', 'Lanã', 'Darê'),
('Bará', 'Lanã', 'Emí'),
('Bará', 'Lanã', 'Funiqué'),
('Bará', 'Lanã', 'Haraxê'),
('Bará', 'Lanã', 'Hô'),
('Bará', 'Lanã', 'Homí'),
('Bará', 'Lanã', 'Krajeú'),
('Bará', 'Lanã', 'Kaminoloa'),
('Bará', 'Lanã', 'Laqué'),
('Bará', 'Lanã', 'Mí'),
('Bará', 'Lanã', 'Odeí'),
('Bará', 'Lanã', 'Omulúm'),
('Bará', 'Lanã', 'Tukí'),
('Bará', 'Lanã', 'Tirirí'),
('Bará', 'Lanã', 'Tiriri-lanã'),

-- OGUM AVAGÃ
('Ogum', 'Avagã', 'Adeí'),
('Ogum', 'Avagã', 'Abedê'),
('Ogum', 'Avagã', 'Adiolá'),
('Ogum', 'Avagã', 'Beí'),
('Ogum', 'Avagã', 'Bomaté'),
('Ogum', 'Avagã', 'Doveí'),
('Ogum', 'Avagã', 'Deí'),
('Ogum', 'Avagã', 'Elefá'),
('Ogum', 'Avagã', 'Elunã'),
('Ogum', 'Avagã', 'Jarê'),
('Ogum', 'Avagã', 'Onira'),
('Ogum', 'Avagã', 'Olobedê'),
('Ogum', 'Avagã', 'Peremí'),
('Ogum', 'Avagã', 'Roneí'),
('Ogum', 'Avagã', 'Riolú'),

-- OGUM ONIRA
('Ogum', 'Onira', 'Adiocô'),
('Ogum', 'Onira', 'Adiolá'),
('Ogum', 'Onira', 'Avagã'),
('Ogum', 'Onira', 'Bolá'),
('Ogum', 'Onira', 'Beí'),
('Ogum', 'Onira', 'Djobí'),
('Ogum', 'Onira', 'Doveí'),
('Ogum', 'Onira', 'Darê'),
('Ogum', 'Onira', 'Dê'),
('Ogum', 'Onira', 'Luã'),
('Ogum', 'Onira', 'Lobe-dê'),
('Ogum', 'Onira', 'Malê'),
('Ogum', 'Onira', 'Olobedê'),
('Ogum', 'Onira', 'Obiratã'),
('Ogum', 'Onira', 'Peremí'),

-- OGUM OLOBEDÊ
('Ogum', 'Olobedê', 'Anirê'),
('Ogum', 'Olobedê', 'Adio-laia'),
('Ogum', 'Olobedê', 'Avagã'),
('Ogum', 'Olobedê', 'Adiolá'),
('Ogum', 'Olobedê', 'Abedê'),
('Ogum', 'Olobedê', 'Bomaté'),
('Ogum', 'Olobedê', 'Bomí'),
('Ogum', 'Olobedê', 'Cassadójo'),
('Ogum', 'Olobedê', 'Darê'),
('Ogum', 'Olobedê', 'Elefá'),
('Ogum', 'Olobedê', 'Irajê'),
('Ogum', 'Olobedê', 'Miremí'),
('Ogum', 'Olobedê', 'Naruê'),
('Ogum', 'Olobedê', 'Onira'),
('Ogum', 'Olobedê', 'Onira-adiolá'),

-- OGUM ADIOLÁ
('Ogum', 'Adiolá', 'Adeíba'),
('Ogum', 'Adiolá', 'Adeí'),
('Ogum', 'Adiolá', 'Avagã'),
('Ogum', 'Adiolá', 'Birí'),
('Ogum', 'Adiolá', 'Bomí'),
('Ogum', 'Adiolá', 'Bolá'),
('Ogum', 'Adiolá', 'Dê'),
('Ogum', 'Adiolá', 'Jarê'),
('Ogum', 'Adiolá', 'Lecí'),
('Ogum', 'Adiolá', 'Megê'),
('Ogum', 'Adiolá', 'Nira'),
('Ogum', 'Adiolá', 'Onirê'),
('Ogum', 'Adiolá', 'Onira'),
('Ogum', 'Adiolá', 'Olobedê'),
('Ogum', 'Adiolá', 'Omí'),
('Ogum', 'Adiolá', 'Onira-olobedê'),
('Ogum', 'Adiolá', 'Omim-marê'),
('Ogum', 'Adiolá', 'Riolú'),

-- OYÁ TIMBOÁ
('Oyá', 'Timboá', 'Bará-tenã'),
('Oyá', 'Timboá', 'Balê'),
('Oyá', 'Timboá', 'Dilajá'),
('Oyá', 'Timboá', 'Daní'),
('Oyá', 'Timboá', 'Difí'),
('Oyá', 'Timboá', 'Kitala'),
('Oyá', 'Timboá', 'Lajá'),
('Oyá', 'Timboá', 'Odá'),
('Oyá', 'Timboá', 'Tofan'),

-- OYÁ DIRÁ
('Oyá', 'Dirá', 'Akí'),
('Oyá', 'Dirá', 'Bomí-micê'),
('Oyá', 'Dirá', 'Cará'),
('Oyá', 'Dirá', 'Dilajá'),
('Oyá', 'Dirá', 'Daní'),
('Oyá', 'Dirá', 'Ditolá'),
('Oyá', 'Dirá', 'Dilaim'),
('Oyá', 'Dirá', 'Difí'),
('Oyá', 'Dirá', 'Fumí'),
('Oyá', 'Dirá', 'Lajá'),
('Oyá', 'Dirá', 'Micê'),
('Oyá', 'Dirá', 'Miguê'),
('Oyá', 'Dirá', 'Tofan'),

-- OYÁ NIQUÊ
('Oyá', 'Niquê', 'Abedê'),
('Oyá', 'Niquê', 'Akí'),
('Oyá', 'Niquê', 'Bolá'),
('Oyá', 'Niquê', 'Cará'),
('Oyá', 'Niquê', 'Diolá'),
('Oyá', 'Niquê', 'Diuá'),
('Oyá', 'Niquê', 'Di-beijí'),
('Oyá', 'Niquê', 'Delê'),
('Oyá', 'Niquê', 'Dê'),
('Oyá', 'Niquê', 'Difí'),
('Oyá', 'Niquê', 'Dilaim'),
('Oyá', 'Niquê', 'Emí'),
('Oyá', 'Niquê', 'Lajá'),
('Oyá', 'Niquê', 'Latê'),
('Oyá', 'Niquê', 'Ladê'),
('Oyá', 'Niquê', 'Miguê'),
('Oyá', 'Niquê', 'Mí'),
('Oyá', 'Niquê', 'Miuá'),
('Oyá', 'Niquê', 'Micê'),
('Oyá', 'Niquê', 'Nirê'),
('Oyá', 'Niquê', 'Ninã'),
('Oyá', 'Niquê', 'Tofan'),
('Oyá', 'Niquê', 'Tolá'),

-- IANSÃ (sem qualidade específica — qualidade = 'Iansã')
('Iansã', 'Iansã', 'Bomí'),
('Iansã', 'Iansã', 'Bomí-micê'),
('Iansã', 'Iansã', 'Bará-tenã'),
('Iansã', 'Iansã', 'Demí'),
('Iansã', 'Iansã', 'Ditolá'),
('Iansã', 'Iansã', 'Diodá'),
('Iansã', 'Iansã', 'Dilajá'),
('Iansã', 'Iansã', 'Deí'),
('Iansã', 'Iansã', 'Doaê'),
('Iansã', 'Iansã', 'Funiqué'),
('Iansã', 'Iansã', 'Iomí'),
('Iansã', 'Iansã', 'Kitala'),
('Iansã', 'Iansã', 'Ladiá'),
('Iansã', 'Iansã', 'Mitolá'),
('Iansã', 'Iansã', 'Miodá'),
('Iansã', 'Iansã', 'Mirê'),
('Iansã', 'Iansã', 'Miremí'),
('Iansã', 'Iansã', 'Niquê'),
('Iansã', 'Iansã', 'Odá'),
('Iansã', 'Iansã', 'Sessú'),
('Iansã', 'Iansã', 'Taladê'),

-- XANGÔ AGANJÚ IBEJÊ
('Xangô', 'Aganjú Ibejê', 'Awá'),
('Xangô', 'Aganjú Ibejê', 'Açuã'),
('Xangô', 'Aganjú Ibejê', 'Baim'),
('Xangô', 'Aganjú Ibejê', 'Barú'),
('Xangô', 'Aganjú Ibejê', 'Deí'),
('Xangô', 'Aganjú Ibejê', 'Doum'),
('Xangô', 'Aganjú Ibejê', 'Dolua-midi-omí'),
('Xangô', 'Aganjú Ibejê', 'Irá'),
('Xangô', 'Aganjú Ibejê', 'Luá'),
('Xangô', 'Aganjú Ibejê', 'Midiomí'),
('Xangô', 'Aganjú Ibejê', 'Midi-omí-oduluá'),
('Xangô', 'Aganjú Ibejê', 'Oduluá'),
('Xangô', 'Aganjú Ibejê', 'Omí'),
('Xangô', 'Aganjú Ibejê', 'Oduluá-midi-omí'),
('Xangô', 'Aganjú Ibejê', 'Tokí'),
('Xangô', 'Aganjú Ibejê', 'Tokiú'),
('Xangô', 'Aganjú Ibejê', 'Toquim'),
('Xangô', 'Aganjú Ibejê', 'Tuquê'),

-- XANGÔ AGANJÚ
('Xangô', 'Aganjú', 'Açuã'),
('Xangô', 'Aganjú', 'Bolá'),
('Xangô', 'Aganjú', 'Boboxê'),
('Xangô', 'Aganjú', 'Bibolá'),
('Xangô', 'Aganjú', 'Baim'),
('Xangô', 'Aganjú', 'Bomí'),
('Xangô', 'Aganjú', 'Barú'),
('Xangô', 'Aganjú', 'Deí'),
('Xangô', 'Aganjú', 'Demí'),
('Xangô', 'Aganjú', 'Delê'),
('Xangô', 'Aganjú', 'Dopan'),
('Xangô', 'Aganjú', 'Doluar'),
('Xangô', 'Aganjú', 'Emí'),
('Xangô', 'Aganjú', 'Fukê'),
('Xangô', 'Aganjú', 'Fumilayô'),
('Xangô', 'Aganjú', 'Herí'),
('Xangô', 'Aganjú', 'Idê'),
('Xangô', 'Aganjú', 'Irá'),
('Xangô', 'Aganjú', 'Lelê'),
('Xangô', 'Aganjú', 'Muquê'),
('Xangô', 'Aganjú', 'Mací'),
('Xangô', 'Aganjú', 'Mukê'),
('Xangô', 'Aganjú', 'Odeí'),
('Xangô', 'Aganjú', 'Oloxê'),
('Xangô', 'Aganjú', 'Oí'),
('Xangô', 'Aganjú', 'Okô-axé'),
('Xangô', 'Aganjú', 'Toiô-elê'),
('Xangô', 'Aganjú', 'Toelê'),
('Xangô', 'Aganjú', 'Toió'),
('Xangô', 'Aganjú', 'Tuquê'),
('Xangô', 'Aganjú', 'Tukí'),
('Xangô', 'Aganjú', 'Unã'),

-- XANGÔ AGODÔ
('Xangô', 'Agodô', 'Aluá'),
('Xangô', 'Agodô', 'Aloxê'),
('Xangô', 'Agodô', 'Abaluá'),
('Xangô', 'Agodô', 'Amalaci'),
('Xangô', 'Agodô', 'Abaduamí'),
('Xangô', 'Agodô', 'Baruálofina'),
('Xangô', 'Agodô', 'Babá-alafim'),
('Xangô', 'Agodô', 'Bamboxê'),
('Xangô', 'Agodô', 'Boboxê'),
('Xangô', 'Agodô', 'Babá-orofina'),
('Xangô', 'Agodô', 'Doluá'),
('Xangô', 'Agodô', 'Dadá'),
('Xangô', 'Agodô', 'Edumbadeí'),
('Xangô', 'Agodô', 'Iwá'),
('Xangô', 'Agodô', 'Klaobê'),
('Xangô', 'Agodô', 'Kamucá'),
('Xangô', 'Agodô', 'Luá'),
('Xangô', 'Agodô', 'Lofina'),
('Xangô', 'Agodô', 'Odumbadeí'),
('Xangô', 'Agodô', 'Oloquê'),
('Xangô', 'Agodô', 'Olofukê'),
('Xangô', 'Agodô', 'Odemá'),
('Xangô', 'Agodô', 'Oko-axé'),
('Xangô', 'Agodô', 'Sabalujá'),
('Xangô', 'Agodô', 'Toqui'),
('Xangô', 'Agodô', 'Taiô'),
('Xangô', 'Agodô', 'Tokí'),
('Xangô', 'Agodô', 'Toquim'),
('Xangô', 'Agodô', 'Zanzadureí'),

-- OTIM (sem qualidade — qualidade = 'Otim')
('Otim', 'Otim', 'Abelujam'),
('Otim', 'Otim', 'Abaim'),
('Otim', 'Otim', 'Alê'),
('Otim', 'Otim', 'Burú'),
('Otim', 'Otim', 'Belujam'),
('Otim', 'Otim', 'Bilade'),
('Otim', 'Otim', 'Bomí'),
('Otim', 'Otim', 'Cadinã'),
('Otim', 'Otim', 'Cardinam'),
('Otim', 'Otim', 'Dirê'),
('Otim', 'Otim', 'Deí'),
('Otim', 'Otim', 'Dê'),
('Otim', 'Otim', 'Elefaburú'),
('Otim', 'Otim', 'Emí'),
('Otim', 'Otim', 'Indê'),
('Otim', 'Otim', 'Jipê'),
('Otim', 'Otim', 'Labiá'),
('Otim', 'Otim', 'Latê'),
('Otim', 'Otim', 'Ludú'),
('Otim', 'Otim', 'Malê'),
('Otim', 'Otim', 'Miremí'),
('Otim', 'Otim', 'Mirê'),
('Otim', 'Otim', 'Mí'),
('Otim', 'Otim', 'Omiburú'),
('Otim', 'Otim', 'Oberemí'),
('Otim', 'Otim', 'Omintundê'),
('Otim', 'Otim', 'Omialê'),
('Otim', 'Otim', 'Omí'),
('Otim', 'Otim', 'Omimalê'),
('Otim', 'Otim', 'Omimarú'),
('Otim', 'Otim', 'Ride'),
('Otim', 'Otim', 'Tindê'),

-- ODÉ (sem qualidade — qualidade = 'Odé')
('Odé', 'Odé', 'Abelujam'),
('Odé', 'Odé', 'Abaim'),
('Odé', 'Odé', 'Alê'),
('Odé', 'Odé', 'Burú'),
('Odé', 'Odé', 'Belujam'),
('Odé', 'Odé', 'Bilade'),
('Odé', 'Odé', 'Bomí'),
('Odé', 'Odé', 'Cadinã'),
('Odé', 'Odé', 'Cardinam'),
('Odé', 'Odé', 'Dirê'),
('Odé', 'Odé', 'Deí'),
('Odé', 'Odé', 'Dê'),
('Odé', 'Odé', 'Elefaburú'),
('Odé', 'Odé', 'Emí'),
('Odé', 'Odé', 'Indê'),
('Odé', 'Odé', 'Jipê'),
('Odé', 'Odé', 'Labiá'),
('Odé', 'Odé', 'Latê'),
('Odé', 'Odé', 'Ludú'),
('Odé', 'Odé', 'Malê'),
('Odé', 'Odé', 'Miremí'),
('Odé', 'Odé', 'Mirê'),
('Odé', 'Odé', 'Mí'),
('Odé', 'Odé', 'Omiburú'),
('Odé', 'Odé', 'Oberemí'),
('Odé', 'Odé', 'Omintundê'),
('Odé', 'Odé', 'Omialê'),
('Odé', 'Odé', 'Omí'),
('Odé', 'Odé', 'Omimalê'),
('Odé', 'Odé', 'Omimarú'),
('Odé', 'Odé', 'Ride'),
('Odé', 'Odé', 'Tindê'),

-- OSSANHA (sem qualidade — qualidade = 'Ossanha')
('Ossanha', 'Ossanha', 'Aquê'),
('Ossanha', 'Ossanha', 'Ajubê'),
('Ossanha', 'Ossanha', 'Ambí'),
('Ossanha', 'Ossanha', 'Bí'),
('Ossanha', 'Ossanha', 'Beremim'),
('Ossanha', 'Ossanha', 'Beremim-ossé'),
('Ossanha', 'Ossanha', 'Benedí'),
('Ossanha', 'Ossanha', 'Baduê'),
('Ossanha', 'Ossanha', 'Beremí'),
('Ossanha', 'Ossanha', 'Dequê'),
('Ossanha', 'Ossanha', 'Dompê'),
('Ossanha', 'Ossanha', 'Difí'),
('Ossanha', 'Ossanha', 'Fumaguê'),
('Ossanha', 'Ossanha', 'Guê'),
('Ossanha', 'Ossanha', 'Guetemã'),
('Ossanha', 'Ossanha', 'Lajupê'),
('Ossanha', 'Ossanha', 'Miguê'),
('Ossanha', 'Ossanha', 'Miuá'),
('Ossanha', 'Ossanha', 'Malê'),
('Ossanha', 'Ossanha', 'Niquê'),
('Ossanha', 'Ossanha', 'Obiotá'),
('Ossanha', 'Ossanha', 'Ossí'),
('Ossanha', 'Ossanha', 'Osanibim'),
('Ossanha', 'Ossanha', 'Oguniquê'),
('Ossanha', 'Ossanha', 'Rá'),
('Ossanha', 'Ossanha', 'Seká'),
('Ossanha', 'Ossanha', 'Sereubá'),
('Ossanha', 'Ossanha', 'Tolá'),
('Ossanha', 'Ossanha', 'Tunexê'),
('Ossanha', 'Ossanha', 'Tumichê'),

-- OBÁ (sem qualidade — qualidade = 'Obá')
('Obá', 'Obá', 'Axurum'),
('Obá', 'Obá', 'Bomí'),
('Obá', 'Obá', 'Beremim-omí'),
('Obá', 'Obá', 'Dê'),
('Obá', 'Obá', 'Daí'),
('Obá', 'Obá', 'Demim'),
('Obá', 'Obá', 'Fumí'),
('Obá', 'Obá', 'Fumí-layô'),
('Obá', 'Obá', 'Fumí-otá'),
('Obá', 'Obá', 'Fumilakê'),
('Obá', 'Obá', 'Koemí'),
('Obá', 'Obá', 'Layô'),
('Obá', 'Obá', 'Ladê'),
('Obá', 'Obá', 'Labaê'),
('Obá', 'Obá', 'Ladiá'),
('Obá', 'Obá', 'Lafim'),
('Obá', 'Obá', 'Lukê'),
('Obá', 'Obá', 'Lubemí'),
('Obá', 'Obá', 'Mirê'),
('Obá', 'Obá', 'Mideí'),
('Obá', 'Obá', 'Nikê'),
('Obá', 'Obá', 'Nafioquê'),
('Obá', 'Obá', 'Olomí-otá'),
('Obá', 'Obá', 'Olomí'),
('Obá', 'Obá', 'Suemí'),
('Obá', 'Obá', 'Sumí-otá'),
('Obá', 'Obá', 'Soarê'),
('Obá', 'Obá', 'Taladê'),

-- XAPANÃ JUBETEI
('Xapanã', 'Jubetei', 'Atá-udê'),
('Xapanã', 'Jubetei', 'Bolá'),
('Xapanã', 'Jubetei', 'Djobí'),
('Xapanã', 'Jubetei', 'Dionã'),
('Xapanã', 'Jubetei', 'Djobí-toió'),
('Xapanã', 'Jubetei', 'Djobí-teum'),
('Xapanã', 'Jubetei', 'Dompê'),
('Xapanã', 'Jubetei', 'Inatá'),
('Xapanã', 'Jubetei', 'Idu-ôfã'),
('Xapanã', 'Jubetei', 'Jobioní'),
('Xapanã', 'Jubetei', 'Jubeteó'),
('Xapanã', 'Jubetei', 'Jobí-teiú'),
('Xapanã', 'Jubetei', 'Jobí'),
('Xapanã', 'Jubetei', 'Omí-dompê'),
('Xapanã', 'Jubetei', 'Obô-robô'),
('Xapanã', 'Jubetei', 'Tanhã'),
('Xapanã', 'Jubetei', 'Tonhô'),
('Xapanã', 'Jubetei', 'Teum'),
('Xapanã', 'Jubetei', 'Udê'),

-- XAPANÃ BELUJÁ
('Xapanã', 'Belujá', 'Irocô'),
('Xapanã', 'Belujá', 'Mido-sum'),
('Xapanã', 'Belujá', 'Orocô'),
('Xapanã', 'Belujá', 'Onirobô'),
('Xapanã', 'Belujá', 'Omimarum'),
('Xapanã', 'Belujá', 'Obeloní'),
('Xapanã', 'Belujá', 'Obe-oní'),
('Xapanã', 'Belujá', 'Obemim'),
('Xapanã', 'Belujá', 'Obe-jobí'),
('Xapanã', 'Belujá', 'Obeteum'),
('Xapanã', 'Belujá', 'Obetoió'),
('Xapanã', 'Belujá', 'Omimbolá'),
('Xapanã', 'Belujá', 'Obe-emim'),
('Xapanã', 'Belujá', 'Omidê'),
('Xapanã', 'Belujá', 'Omirô'),
('Xapanã', 'Belujá', 'Omiorobô'),
('Xapanã', 'Belujá', 'Omí-barum'),
('Xapanã', 'Belujá', 'Omo-robô'),
('Xapanã', 'Belujá', 'Obirabará'),
('Xapanã', 'Belujá', 'Okô'),
('Xapanã', 'Belujá', 'Omitoió'),
('Xapanã', 'Belujá', 'Toió'),
('Xapanã', 'Belujá', 'Teiú'),

-- XAPANÃ SAPATÁ
('Xapanã', 'Sapatá', 'Ajorotóm'),
('Xapanã', 'Sapatá', 'Baruê'),
('Xapanã', 'Sapatá', 'Costasum'),
('Xapanã', 'Sapatá', 'Costasanfrê'),
('Xapanã', 'Sapatá', 'Costabaruê'),
('Xapanã', 'Sapatá', 'Costasunsê'),
('Xapanã', 'Sapatá', 'Djam-djam'),
('Xapanã', 'Sapatá', 'Gama'),
('Xapanã', 'Sapatá', 'Guanguãna'),
('Xapanã', 'Sapatá', 'Guenví'),
('Xapanã', 'Sapatá', 'Obi-robô'),
('Xapanã', 'Sapatá', 'Obi-taió'),
('Xapanã', 'Sapatá', 'Obi-ti-udê'),
('Xapanã', 'Sapatá', 'Olokô'),
('Xapanã', 'Sapatá', 'Obi-tunjê'),
('Xapanã', 'Sapatá', 'Obibolá'),
('Xapanã', 'Sapatá', 'Obi-alê'),

-- OXUM IBEJÊ
('Oxum', 'Ibejê', 'Aguidá'),
('Oxum', 'Ibejê', 'Aguidá-mí'),
('Oxum', 'Ibejê', 'Bomí'),
('Oxum', 'Ibejê', 'Digama'),
('Oxum', 'Ibejê', 'Dudú'),
('Oxum', 'Ibejê', 'Dê'),
('Oxum', 'Ibejê', 'Didú'),
('Oxum', 'Ibejê', 'Demí'),
('Oxum', 'Ibejê', 'Diní'),
('Oxum', 'Ibejê', 'Dinibomí'),
('Oxum', 'Ibejê', 'Dewê'),
('Oxum', 'Ibejê', 'Diniomí'),
('Oxum', 'Ibejê', 'Dinilomí'),
('Oxum', 'Ibejê', 'Dioni'),
('Oxum', 'Ibejê', 'Dionicí'),
('Oxum', 'Ibejê', 'Decí'),
('Oxum', 'Ibejê', 'Deí'),
('Oxum', 'Ibejê', 'Iomã'),
('Oxum', 'Ibejê', 'Iocí'),
('Oxum', 'Ibejê', 'Ie ie erichê'),
('Oxum', 'Ibejê', 'Locí'),
('Oxum', 'Ibejê', 'Maré'),
('Oxum', 'Ibejê', 'Miuá'),
('Oxum', 'Ibejê', 'Mobomí'),
('Oxum', 'Ibejê', 'Mirê'),
('Oxum', 'Ibejê', 'Ninã'),
('Oxum', 'Ibejê', 'Niná-demí'),
('Oxum', 'Ibejê', 'Omiolobá'),
('Oxum', 'Ibejê', 'Ocí'),
('Oxum', 'Ibejê', 'Olomí'),
('Oxum', 'Ibejê', 'Olobomí'),
('Oxum', 'Ibejê', 'Olocim'),

-- OXUM PANDÁ
('Oxum', 'Pandá', 'Aguidá'),
('Oxum', 'Pandá', 'Aguidá-mí'),
('Oxum', 'Pandá', 'Adimun'),
('Oxum', 'Pandá', 'Bomí'),
('Oxum', 'Pandá', 'Beremí'),
('Oxum', 'Pandá', 'Dê'),
('Oxum', 'Pandá', 'Deí'),
('Oxum', 'Pandá', 'Demun'),
('Oxum', 'Pandá', 'Decí'),
('Oxum', 'Pandá', 'Dionicí'),
('Oxum', 'Pandá', 'Dioní'),
('Oxum', 'Pandá', 'Dewê'),
('Oxum', 'Pandá', 'Diniomí'),
('Oxum', 'Pandá', 'Dinilomí'),
('Oxum', 'Pandá', 'Diní'),
('Oxum', 'Pandá', 'Dinibomí'),
('Oxum', 'Pandá', 'Didú'),
('Oxum', 'Pandá', 'Demí'),
('Oxum', 'Pandá', 'Dudú'),
('Oxum', 'Pandá', 'Digama'),
('Oxum', 'Pandá', 'Ie le Erichê'),
('Oxum', 'Pandá', 'Iocí'),
('Oxum', 'Pandá', 'Iomã'),
('Oxum', 'Pandá', 'Lomí'),
('Oxum', 'Pandá', 'Locí'),
('Oxum', 'Pandá', 'Mobomí'),
('Oxum', 'Pandá', 'Miuá'),
('Oxum', 'Pandá', 'Mirê'),
('Oxum', 'Pandá', 'Maré'),
('Oxum', 'Pandá', 'Niná'),
('Oxum', 'Pandá', 'Niná-demí'),
('Oxum', 'Pandá', 'Olobomí'),
('Oxum', 'Pandá', 'Olomí'),
('Oxum', 'Pandá', 'Olocim'),
('Oxum', 'Pandá', 'Ocí'),
('Oxum', 'Pandá', 'Omiuá'),
('Oxum', 'Pandá', 'Olobá'),
('Oxum', 'Pandá', 'Omibolá'),
('Oxum', 'Pandá', 'Tuké'),

-- OXUM DEMUN
('Oxum', 'Demun', 'Aminarê'),
('Oxum', 'Demun', 'Alaôro'),
('Oxum', 'Demun', 'Dokô'),
('Oxum', 'Demun', 'Adimun-idê'),
('Oxum', 'Demun', 'Bambalá'),
('Oxum', 'Demun', 'Bambalawebo'),
('Oxum', 'Demun', 'Beremim-omí'),
('Oxum', 'Demun', 'Dã'),
('Oxum', 'Demun', 'Duô'),
('Oxum', 'Demun', 'Emiremí'),
('Oxum', 'Demun', 'Emireomí'),
('Oxum', 'Demun', 'Emilomí'),
('Oxum', 'Demun', 'Emibomí'),
('Oxum', 'Demun', 'Emiomã'),
('Oxum', 'Demun', 'Emiocí'),
('Oxum', 'Demun', 'Emiodaça'),
('Oxum', 'Demun', 'Emiomí'),
('Oxum', 'Demun', 'Emiuê'),
('Oxum', 'Demun', 'Iaôro'),
('Oxum', 'Demun', 'Ludú'),
('Oxum', 'Demun', 'Miremí'),
('Oxum', 'Demun', 'Mirê'),
('Oxum', 'Demun', 'Oní'),
('Oxum', 'Demun', 'Olobá'),
('Oxum', 'Demun', 'Omí'),
('Oxum', 'Demun', 'Olelê-omí'),
('Oxum', 'Demun', 'Orugã'),
('Oxum', 'Demun', 'Raçanã'),
('Oxum', 'Demun', 'Uiagadê'),

-- OXUM OLOBÁ
('Oxum', 'Olobá', 'Atolá'),
('Oxum', 'Olobá', 'Adocô'),
('Oxum', 'Olobá', 'Bomí'),
('Oxum', 'Olobá', 'Carurum'),
('Oxum', 'Olobá', 'Carurum-bolá'),
('Oxum', 'Olobá', 'Diuá'),
('Oxum', 'Olobá', 'Dopon'),
('Oxum', 'Olobá', 'Duô'),
('Oxum', 'Olobá', 'Delê'),
('Oxum', 'Olobá', 'Diniocí'),
('Oxum', 'Olobá', 'Diniobí'),
('Oxum', 'Olobá', 'Diniodá'),
('Oxum', 'Olobá', 'Dinioá'),
('Oxum', 'Olobá', 'Dokô'),
('Oxum', 'Olobá', 'Emí'),
('Oxum', 'Olobá', 'Epandá'),
('Oxum', 'Olobá', 'Icári'),
('Oxum', 'Olobá', 'Iecariô'),
('Oxum', 'Olobá', 'Iaôro'),
('Oxum', 'Olobá', 'Ladiá'),
('Oxum', 'Olobá', 'Lobe-edé'),
('Oxum', 'Olobá', 'Miuá'),
('Oxum', 'Olobá', 'Midéle'),
('Oxum', 'Olobá', 'Niqué'),
('Oxum', 'Olobá', 'Odá'),
('Oxum', 'Olobá', 'Oló'),
('Oxum', 'Olobá', 'Omiorô-oní'),
('Oxum', 'Olobá', 'Omilokum'),
('Oxum', 'Olobá', 'Orô'),
('Oxum', 'Olobá', 'Omi-lokum-idê'),
('Oxum', 'Olobá', 'Tarai-dê'),

-- OXUM DOCÔ
('Oxum', 'Docô', 'Adimun'),
('Oxum', 'Docô', 'Bambalá'),
('Oxum', 'Docô', 'Bocô'),
('Oxum', 'Docô', 'Dudú'),
('Oxum', 'Docô', 'Emiluá'),
('Oxum', 'Docô', 'Emí'),
('Oxum', 'Docô', 'Ie le Dokô'),
('Oxum', 'Docô', 'Ie le Cari'),
('Oxum', 'Docô', 'Laké'),
('Oxum', 'Docô', 'Lokum-idê'),
('Oxum', 'Docô', 'Midéle'),
('Oxum', 'Docô', 'Miniouá'),
('Oxum', 'Docô', 'Miniocí'),
('Oxum', 'Docô', 'Miniolí'),
('Oxum', 'Docô', 'Nanã'),
('Oxum', 'Docô', 'Omiorô'),
('Oxum', 'Docô', 'Oní-bibolá'),
('Oxum', 'Docô', 'Odá'),
('Oxum', 'Docô', 'Olí'),
('Oxum', 'Docô', 'Omiodaça'),
('Oxum', 'Docô', 'Olobá'),
('Oxum', 'Docô', 'Omi-lokum'),
('Oxum', 'Docô', 'Omiorô-oní'),
('Oxum', 'Docô', 'Oromí'),
('Oxum', 'Docô', 'Ocí'),
('Oxum', 'Docô', 'Omidocô'),
('Oxum', 'Docô', 'Tiomí'),
('Oxum', 'Docô', 'Tiodaça'),
('Oxum', 'Docô', 'Tiolá'),
('Oxum', 'Docô', 'Taladê'),
('Oxum', 'Docô', 'Talabí'),
('Oxum', 'Docô', 'Tualê'),

-- YEMANJÁ BOCÍ
('Yemanjá', 'Bocí', 'Afobocí'),
('Yemanjá', 'Bocí', 'Afalomí'),
('Yemanjá', 'Bocí', 'Afatoá'),
('Yemanjá', 'Bocí', 'Afatolá'),
('Yemanjá', 'Bocí', 'Afaocí'),
('Yemanjá', 'Bocí', 'Afací'),
('Yemanjá', 'Bocí', 'Afaemí'),
('Yemanjá', 'Bocí', 'Afami'),
('Yemanjá', 'Bocí', 'Afatobí'),
('Yemanjá', 'Bocí', 'Aebocí'),
('Yemanjá', 'Bocí', 'Aelomí'),
('Yemanjá', 'Bocí', 'Aeocí'),
('Yemanjá', 'Bocí', 'Aetobí'),
('Yemanjá', 'Bocí', 'Afayabá'),
('Yemanjá', 'Bocí', 'Agomaré'),
('Yemanjá', 'Bocí', 'Akré'),
('Yemanjá', 'Bocí', 'Bemiké'),
('Yemanjá', 'Bocí', 'Beremí'),
('Yemanjá', 'Bocí', 'Bomí'),
('Yemanjá', 'Bocí', 'Djabocí'),
('Yemanjá', 'Bocí', 'Dilê'),
('Yemanjá', 'Bocí', 'Emiodô'),
('Yemanjá', 'Bocí', 'Emiremí'),
('Yemanjá', 'Bocí', 'Emitobí'),
('Yemanjá', 'Bocí', 'Emiocí'),
('Yemanjá', 'Bocí', 'Emeremí'),
('Yemanjá', 'Bocí', 'Emitoalê'),
('Yemanjá', 'Bocí', 'Emiké'),
('Yemanjá', 'Bocí', 'Ialé'),
('Yemanjá', 'Bocí', 'Iakerê'),
('Yemanjá', 'Bocí', 'Iakejá'),
('Yemanjá', 'Bocí', 'Lobocí'),
('Yemanjá', 'Bocí', 'Ladê'),
('Yemanjá', 'Bocí', 'Miremí'),
('Yemanjá', 'Bocí', 'Mitoalê'),
('Yemanjá', 'Bocí', 'Mike'),
('Yemanjá', 'Bocí', 'Mirê'),
('Yemanjá', 'Bocí', 'Nanã'),
('Yemanjá', 'Bocí', 'Niná'),
('Yemanjá', 'Bocí', 'Odoaxê'),
('Yemanjá', 'Bocí', 'Obí'),
('Yemanjá', 'Bocí', 'Olobocí'),
('Yemanjá', 'Bocí', 'Ocí'),
('Yemanjá', 'Bocí', 'Olocí'),
('Yemanjá', 'Bocí', 'Olomiké'),
('Yemanjá', 'Bocí', 'Sessun'),
('Yemanjá', 'Bocí', 'Tobí'),
('Yemanjá', 'Bocí', 'Toalê'),
('Yemanjá', 'Bocí', 'Yabocí'),

-- YEMANJÁ BOMÍ
('Yemanjá', 'Bomí', 'Aebomí'),
('Yemanjá', 'Bomí', 'Afaomí'),
('Yemanjá', 'Bomí', 'Afamiô'),
('Yemanjá', 'Bomí', 'Afabomi'),
('Yemanjá', 'Bomí', 'Aeomí'),
('Yemanjá', 'Bomí', 'Bocí'),
('Yemanjá', 'Bomí', 'Domí'),
('Yemanjá', 'Bomí', 'Emiomí'),
('Yemanjá', 'Bomí', 'Emilomí'),
('Yemanjá', 'Bomí', 'Emibomí'),
('Yemanjá', 'Bomí', 'Iakelê'),
('Yemanjá', 'Bomí', 'Jaomí'),
('Yemanjá', 'Bomí', 'Jalomí'),
('Yemanjá', 'Bomí', 'Jaobí'),
('Yemanjá', 'Bomí', 'Lomí'),
('Yemanjá', 'Bomí', 'Miniú'),
('Yemanjá', 'Bomí', 'Miremí'),
('Yemanjá', 'Bomí', 'Maré'),
('Yemanjá', 'Bomí', 'Nanã'),
('Yemanjá', 'Bomí', 'Naruá'),
('Yemanjá', 'Bomí', 'Omimaré'),
('Yemanjá', 'Bomí', 'Omidopan'),
('Yemanjá', 'Bomí', 'Omí-ofá'),
('Yemanjá', 'Bomí', 'Omí-anú'),
('Yemanjá', 'Bomí', 'Omitolá'),
('Yemanjá', 'Bomí', 'Olomí'),
('Yemanjá', 'Bomí', 'Omitoalê'),
('Yemanjá', 'Bomí', 'Omí'),
('Yemanjá', 'Bomí', 'Omiocí'),
('Yemanjá', 'Bomí', 'Omiaxê'),
('Yemanjá', 'Bomí', 'Olú'),
('Yemanjá', 'Bomí', 'Rê'),
('Yemanjá', 'Bomí', 'Totolê'),
('Yemanjá', 'Bomí', 'Yabomí'),
('Yemanjá', 'Bomí', 'Yaomí'),

-- YEMANJÁ NANÃ BOROCUM
('Yemanjá', 'Nanã Borocum', 'Afayaomí'),
('Yemanjá', 'Nanã Borocum', 'Domí'),
('Yemanjá', 'Nanã Borocum', 'Domimarú'),
('Yemanjá', 'Nanã Borocum', 'Dopan-naruá'),
('Yemanjá', 'Nanã Borocum', 'Eminanã'),
('Yemanjá', 'Nanã Borocum', 'Iakelê'),
('Yemanjá', 'Nanã Borocum', 'Jalomí'),
('Yemanjá', 'Nanã Borocum', 'Jaomí'),
('Yemanjá', 'Nanã Borocum', 'Jalomirê'),
('Yemanjá', 'Nanã Borocum', 'Ladê'),
('Yemanjá', 'Nanã Borocum', 'Miremio'),
('Yemanjá', 'Nanã Borocum', 'Mikeomí'),
('Yemanjá', 'Nanã Borocum', 'Miniú'),
('Yemanjá', 'Nanã Borocum', 'Nanamí'),
('Yemanjá', 'Nanã Borocum', 'Nanaeu'),
('Yemanjá', 'Nanã Borocum', 'Nanamio'),
('Yemanjá', 'Nanã Borocum', 'Naruá'),
('Yemanjá', 'Nanã Borocum', 'Nakelé'),
('Yemanjá', 'Nanã Borocum', 'Naruá-ibím'),
('Yemanjá', 'Nanã Borocum', 'Omimaré'),
('Yemanjá', 'Nanã Borocum', 'Omí-naruá'),
('Yemanjá', 'Nanã Borocum', 'Olú-omí'),
('Yemanjá', 'Nanã Borocum', 'Omiaxê'),
('Yemanjá', 'Nanã Borocum', 'Rê-omí'),

-- OXALÁ BOCUM
('Oxalá', 'Bocum', 'Atá-u-dê'),
('Oxalá', 'Bocum', 'Alufan'),
('Oxalá', 'Bocum', 'Becum'),
('Oxalá', 'Bocum', 'Bocum'),
('Oxalá', 'Bocum', 'Dacum'),
('Oxalá', 'Bocum', 'Elefan'),
('Oxalá', 'Bocum', 'Efam-deí'),
('Oxalá', 'Bocum', 'Elefan-efam-deí'),
('Oxalá', 'Bocum', 'Falabí'),
('Oxalá', 'Bocum', 'Falufan'),
('Oxalá', 'Bocum', 'Kenchá'),
('Oxalá', 'Bocum', 'Krinã'),
('Oxalá', 'Bocum', 'Nitolê'),
('Oxalá', 'Bocum', 'Orocô'),
('Oxalá', 'Bocum', 'Olocum'),
('Oxalá', 'Bocum', 'Orifan'),
('Oxalá', 'Bocum', 'Odomiaia'),
('Oxalá', 'Bocum', 'Olobojô'),
('Oxalá', 'Bocum', 'Odomaia'),
('Oxalá', 'Bocum', 'Oxeredê'),
('Oxalá', 'Bocum', 'Omibomai'),
('Oxalá', 'Bocum', 'Odomeuí'),
('Oxalá', 'Bocum', 'Odoceuí'),

-- OXALÁ OLOCUM
('Oxalá', 'Olocum', 'Atá-u-dê'),
('Oxalá', 'Olocum', 'Alufan'),
('Oxalá', 'Olocum', 'Becum'),
('Oxalá', 'Olocum', 'Bocum'),
('Oxalá', 'Olocum', 'Dacum'),
('Oxalá', 'Olocum', 'Elefan'),
('Oxalá', 'Olocum', 'Efam-deí'),
('Oxalá', 'Olocum', 'Elefan-efam-deí'),
('Oxalá', 'Olocum', 'Falabí'),
('Oxalá', 'Olocum', 'Falufan'),
('Oxalá', 'Olocum', 'Kenchá'),
('Oxalá', 'Olocum', 'Krinã'),
('Oxalá', 'Olocum', 'Nitolê'),
('Oxalá', 'Olocum', 'Orocô'),
('Oxalá', 'Olocum', 'Obocum'),
('Oxalá', 'Olocum', 'Orifan'),
('Oxalá', 'Olocum', 'Odomiaia'),
('Oxalá', 'Olocum', 'Olobojô'),
('Oxalá', 'Olocum', 'Odomaia'),
('Oxalá', 'Olocum', 'Oxeredê'),
('Oxalá', 'Olocum', 'Omibomai'),
('Oxalá', 'Olocum', 'Odomeuí'),
('Oxalá', 'Olocum', 'Odoceuí'),
('Oxalá', 'Olocum', 'Olomirê'),
('Oxalá', 'Olocum', 'Orifan-efam-deí'),

-- OXALÁ DACUM
('Oxalá', 'Dacum', 'Atá-u-dê'),
('Oxalá', 'Dacum', 'Alufan'),
('Oxalá', 'Dacum', 'Becum'),
('Oxalá', 'Dacum', 'Bocum'),
('Oxalá', 'Dacum', 'Elefan'),
('Oxalá', 'Dacum', 'Efam-deí'),
('Oxalá', 'Dacum', 'Elefan-efam-deí'),
('Oxalá', 'Dacum', 'Falabí'),
('Oxalá', 'Dacum', 'Falufan'),
('Oxalá', 'Dacum', 'Kenchá'),
('Oxalá', 'Dacum', 'Krinã'),
('Oxalá', 'Dacum', 'Nitolê'),
('Oxalá', 'Dacum', 'Orocô'),
('Oxalá', 'Dacum', 'Obocum'),
('Oxalá', 'Dacum', 'Orifan'),
('Oxalá', 'Dacum', 'Odomiaia'),
('Oxalá', 'Dacum', 'Olobojô'),
('Oxalá', 'Dacum', 'Odomaia'),
('Oxalá', 'Dacum', 'Oxeredê'),
('Oxalá', 'Dacum', 'Omibomai'),
('Oxalá', 'Dacum', 'Odomeuí'),
('Oxalá', 'Dacum', 'Odoceuí'),
('Oxalá', 'Dacum', 'Orifan-efam-deí'),

-- OXALÁ JOBOCUM
('Oxalá', 'Jobocum', 'Bô'),
('Oxalá', 'Jobocum', 'Babá'),
('Oxalá', 'Jobocum', 'Bonifan'),
('Oxalá', 'Jobocum', 'Bí'),
('Oxalá', 'Jobocum', 'Babakerê'),
('Oxalá', 'Jobocum', 'Babakejauê'),
('Oxalá', 'Jobocum', 'Ebí'),
('Oxalá', 'Jobocum', 'Elerum'),
('Oxalá', 'Jobocum', 'Grenã'),
('Oxalá', 'Jobocum', 'Idê'),
('Oxalá', 'Jobocum', 'Ibím'),
('Oxalá', 'Jobocum', 'Jibocum'),
('Oxalá', 'Jobocum', 'Kejauê'),
('Oxalá', 'Jobocum', 'Lerô'),
('Oxalá', 'Jobocum', 'Lerum'),
('Oxalá', 'Jobocum', 'Omí'),
('Oxalá', 'Jobocum', 'Onifan'),
('Oxalá', 'Jobocum', 'Omã'),
('Oxalá', 'Jobocum', 'Oromí'),
('Oxalá', 'Jobocum', 'Omilá'),
('Oxalá', 'Jobocum', 'Obí'),
('Oxalá', 'Jobocum', 'Oromilaia'),
('Oxalá', 'Jobocum', 'Orifan'),
('Oxalá', 'Jobocum', 'Obí-omi'),
('Oxalá', 'Jobocum', 'Taladê'),
('Oxalá', 'Jobocum', 'Talabí'),

-- OXALÁ OROMILAIA
('Oxalá', 'Oromilaia', 'Bô'),
('Oxalá', 'Oromilaia', 'Babá'),
('Oxalá', 'Oromilaia', 'Bonifan'),
('Oxalá', 'Oromilaia', 'Bí'),
('Oxalá', 'Oromilaia', 'Babakerê'),
('Oxalá', 'Oromilaia', 'Babakelê'),
('Oxalá', 'Oromilaia', 'Babakejauê'),
('Oxalá', 'Oromilaia', 'Ebí'),
('Oxalá', 'Oromilaia', 'Elerum'),
('Oxalá', 'Oromilaia', 'Grenã'),
('Oxalá', 'Oromilaia', 'Idê'),
('Oxalá', 'Oromilaia', 'Ibím'),
('Oxalá', 'Oromilaia', 'Jibocum'),
('Oxalá', 'Oromilaia', 'Jobocum'),
('Oxalá', 'Oromilaia', 'Kejauê'),
('Oxalá', 'Oromilaia', 'Lerô'),
('Oxalá', 'Oromilaia', 'Lerum'),
('Oxalá', 'Oromilaia', 'Omí'),
('Oxalá', 'Oromilaia', 'Onifan'),
('Oxalá', 'Oromilaia', 'Omã'),
('Oxalá', 'Oromilaia', 'Oromí'),
('Oxalá', 'Oromilaia', 'Omilá'),
('Oxalá', 'Oromilaia', 'Obí'),
('Oxalá', 'Oromilaia', 'Obí-omi'),
('Oxalá', 'Oromilaia', 'Taladê'),
('Oxalá', 'Oromilaia', 'Talabí');

-- =============================================
-- VERIFICAÇÃO: total de registros inseridos
-- =============================================
SELECT orisa, qualidade, COUNT(*) as total_nomes
FROM sobrenomes_orisa
GROUP BY orisa, qualidade
ORDER BY orisa, qualidade;
